import { StyleSheet } from "react-native";

export const PRIMARY = "#1ECF9D";
const BG = "#F5F7F9";
const CARD_BG = "#E8F8F2";
export const TEXT_PRIMARY = "#333";
export const TEXT_SECONDARY = "#999";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: BG },
  scroll: { flex: 1 },
  scrollContent: { paddingBottom: 24, paddingHorizontal: 16 },
  sectionGap: { height: 24 },
  sectionGapLg: { height: 32 },
  profileHeader: { flexDirection: "row", alignItems: "center", padding: 16 },
  profileCard: {
    marginTop: 12,
    borderRadius: 12,
    backgroundColor: CARD_BG,
    overflow: "hidden",
  },
  loginPrompt: {
    paddingVertical: 32,
    paddingHorizontal: 24,
    alignItems: "center",
  },
  loginTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: TEXT_PRIMARY,
    marginBottom: 8,
  },
  loginDesc: {
    fontSize: 14,
    color: TEXT_SECONDARY,
    marginBottom: 24,
  },
  loginBtn: {
    borderRadius: 20,
    paddingHorizontal: 32,
    backgroundColor: PRIMARY,
  },
  avatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: PRIMARY,
    alignItems: "center",
    justifyContent: "center",
  },
  avatarText: { fontSize: 20, fontWeight: "600", color: "#fff" },
  headerTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginLeft: 12,
  },
  userName: { fontSize: 18, fontWeight: "600", color: TEXT_PRIMARY },
  gridCard: {
    borderRadius: 12,
    backgroundColor: "#fff",
    paddingVertical: 12,
    paddingHorizontal: 16,
  },
  gridRow: { flexDirection: "row" },
  gridItem: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 4,
  },
  gridIconWrap: { marginBottom: 2 },
  gridText: { fontSize: 14, color: TEXT_PRIMARY },
  gridCount: { fontSize: 12, color: TEXT_SECONDARY, marginTop: 0 },
  section: {
    backgroundColor: "#fff",
    borderRadius: 12,
    overflow: "hidden",
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: "rgba(0,0,0,0.06)",
  },
  sectionTitle: { fontSize: 16, fontWeight: "600", color: TEXT_PRIMARY },
  sectionMore: { fontSize: 14, color: TEXT_SECONDARY },
  recentScroll: { padding: 16, gap: 12 },
  recentCard: { width: 120, marginRight: 12 },
  recentCover: {
    width: 120,
    height: 120,
    borderRadius: 8,
    backgroundColor: "#E8E8E8",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 8,
  },
  recentTitle: { fontSize: 14, color: TEXT_PRIMARY, fontWeight: "500" },
  recentSubtitle: { fontSize: 12, color: TEXT_SECONDARY, marginTop: 2 },
  playlistThumb: {
    width: 48,
    height: 48,
    borderRadius: 6,
    backgroundColor: "#E8E8E8",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  playlistItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: "rgba(0,0,0,0.06)",
  },
  playlistItemContent: { flex: 1 },
  playlistItemTitle: { fontSize: 16, color: TEXT_PRIMARY },
  playlistMeta: { fontSize: 12, color: TEXT_SECONDARY, marginTop: 2 },
  playlistArrow: { marginLeft: 4 },
});
